config/routes.rb
Rails.application.routes.draw do
  
  resources :events  do
  	resources :comments
  end

  resources :images do
  	resources :comments 
      
    
  end

  resources :blogs do
  	resources :comments
  end
  devise_for :users

  root to:'welcomes#index'
  get '/comments/new', to: 'comments#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Activity</a>
  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">

    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home' , root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'Blog' , blogs_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'Event' , events_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'Image' , images_path, class: "nav-link" %>
      </li>
      <%- if current_user.present? %>
        <li class="nav-item">
          <%= link_to 'Log Out' , destroy_user_session_path, class: 'nav-link', method: :delete %>
        </li>
        <%- else %>
        <li class="nav-item">
          <%= link_to 'Log In' , new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Register' , new_user_registration_path, class: 'nav-link' %>
        </li>
        <%- end %>
    </ul>
    
  </div>
</nav>