config/routes.rb
Rails.application.routes.draw do
  
  resources :events  do
  	resources :comments
  end

  resources :images do
  	resources :comments 
      
    
  end

  resources :blogs do
  	resources :comments
  end
  devise_for :users

  root to:'welcomes#index'
  get '/comments/new', to: 'comments#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	skip_before_action :authenticate_user!
	 def index
	 	@blogs = Blog.all
	 	@images = Image.all
    	@events = Event.all
  end

end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/index.html.erb
<h1> All Blogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="2">Title</th>
      <th colspan="3">Body</th>
      <th colspan="3">Comments</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td colspan="2"><%= blog.title %></td>
        <td colspan="3"><%= blog.body %></td>
        <td colspan="3"> <% blog.comments.each do |comment| %>
           <br/> <u>Name  </u>
            
           <%= comment.name %>
          <br/> <u>Comment</u>
           
           <%= comment.body %>
           <br/>
            <%= link_to 'reply', new_blog_comment_path(blog, parent_id: comment.id) %>
             <br/>
             <% end %>
           <%= link_to ' your comment', new_blog_comment_path(blog) %>
        </td> 
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Comments</th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag image.name.url(:medium) %></td>
       <td> <% image.comments.each do |comment| %>
         <br/> <u>Name  </u>
          <%= comment.name %>
          
           <br/> <u>Comment</u>
           <%= comment.body %>
           <br/>
            <%= link_to 'reply', new_image_comment_path(image, parent_id: comment.id) %>
             <br/>
             <% end %>
            
           <%= link_to 'your comment', new_image_comment_path(image) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Place</th>
      <th>Date</th>
      <th>Description</th>
      <th colspan="3"> Comments</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.place %></td>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
         <td> <% event.comments.each do |comment| %>
           <br/> <u>Name  </u>
          <%= comment.name %>
           <br/> <u>Comment</u>
          
           <%= comment.body %>
           <br/>
            <%= link_to 'reply', new_event_comment_path(event, parent_id: comment.id) %>
             <br/>
             <% end %>
              
           <%= link_to 'your comment', new_event_comment_path(event) %>
        </td>
       
      </tr>
    <% end %>
  </tbody>
</table>